from __future__ import annotations

from argparse import ArgumentParser
from pathlib import Path
from typing import Iterable
import csv
import sys
import time

try:
    from .config import ControllerConfig, PipelineConfig, SwitchConfig, load_controller_config
    from .p4runtime_switch import P4RuntimeSwitch
    from .stats_collector import LockTelemetryDelta, LockTelemetrySnapshot, StatsCollector
except ImportError:  # pragma: no cover - supports `python control_plane/controller.py`
    from config import ControllerConfig, PipelineConfig, SwitchConfig, load_controller_config
    from p4runtime_switch import P4RuntimeSwitch
    from stats_collector import LockTelemetryDelta, LockTelemetrySnapshot, StatsCollector


class Controller:
    """Top-level control-plane process.

    The first milestone is connection management. Statistics collection,
    migration decisions, and table/register programming should be layered on
    top of this class through dedicated modules.
    """

    def __init__(self, config: ControllerConfig):
        self.config = config
        self.switches = {
            switch_config.name: P4RuntimeSwitch(switch_config)
            for switch_config in config.switches
        }

    def connect_all(self) -> None:
        for switch in self.switches.values():
            switch.connect()

    def disconnect_all(self) -> None:
        for switch in reversed(list(self.switches.values())):
            switch.disconnect()

    def connected_switch_names(self) -> list[str]:
        return [
            name
            for name, switch in self.switches.items()
            if switch.connected
        ]

    def collect_telemetry(
        self,
        lock_ids: Iterable[int],
    ) -> dict[str, list[LockTelemetrySnapshot]]:
        return {
            name: StatsCollector(switch).read_locks_telemetry(lock_ids)
            for name, switch in self.switches.items()
        }

    def __enter__(self) -> "Controller":
        self.connect_all()
        return self

    def __exit__(self, exc_type, exc, tb) -> None:
        self.disconnect_all()


def build_single_switch_config(args) -> ControllerConfig:
    pipeline = PipelineConfig(
        p4info_path=Path(args.p4info),
        bmv2_json_path=Path(args.bmv2_json),
    )
    switch = SwitchConfig(
        name=args.name,
        device_id=args.device_id,
        grpc_addr=args.grpc_addr,
        election_id=(args.election_id_high, args.election_id_low),
        thrift_port=args.thrift_port,
        push_pipeline=not args.skip_pipeline_push,
        pipeline=pipeline,
    )
    return ControllerConfig((switch,))


def parse_args(argv: Iterable[str] | None = None):
    parser = ArgumentParser(description="Multi-rack NetLock P4Runtime controller")
    parser.add_argument(
        "--config",
        type=str,
        help="Optional JSON controller config. If omitted, single-switch flags are used.",
    )
    parser.add_argument("--name", default="leaf1", help="Switch name for single-switch mode")
    parser.add_argument("--device-id", type=int, default=1, help="P4Runtime device_id")
    parser.add_argument(
        "--grpc-addr",
        default="127.0.0.1:50001",
        help="P4Runtime server address, e.g. 127.0.0.1:50001",
    )
    parser.add_argument(
        "--thrift-port",
        type=int,
        default=9090,
        help="BMv2 Thrift port for register reads when P4Runtime does not support them.",
    )
    parser.add_argument(
        "--election-id-high",
        type=int,
        default=0,
        help="High 64 bits of P4Runtime controller election ID",
    )
    parser.add_argument(
        "--election-id-low",
        type=int,
        default=1,
        help="Low 64 bits of P4Runtime controller election ID",
    )
    parser.add_argument(
        "--p4info",
        default="build/leaf.p4info.txt",
        help="Path to text-format P4Info generated by p4c",
    )
    parser.add_argument(
        "--bmv2-json",
        default="build/leaf.json",
        help="Path to BMv2 JSON generated by p4c",
    )
    parser.add_argument(
        "--skip-pipeline-push",
        action="store_true",
        help="Connect to an already-programmed switch without pushing the pipeline.",
    )
    parser.add_argument(
        "--stay-connected",
        action="store_true",
        help="Keep the controller alive until Ctrl-C after connecting",
    )
    parser.add_argument(
        "--telemetry-lock-ids",
        type=str,
        help="Comma-separated lock IDs to collect telemetry for, e.g. 1,2,42.",
    )
    parser.add_argument(
        "--telemetry-interval",
        type=float,
        default=1.0,
        help="Seconds between telemetry polls when collecting periodically.",
    )
    parser.add_argument(
        "--telemetry-once",
        action="store_true",
        help="Collect telemetry once and exit.",
    )
    parser.add_argument(
        "--telemetry-output",
        type=str,
        help="Optional CSV output path for telemetry. Defaults to stdout.",
    )
    parser.add_argument(
        "--telemetry-thrift-only",
        action="store_true",
        help="Collect telemetry through BMv2 Thrift without opening P4Runtime.",
    )
    return parser.parse_args(argv)


def main(argv: Iterable[str] | None = None) -> int:
    args = parse_args(argv)
    config = load_controller_config(args.config) if args.config else build_single_switch_config(args)
    config.validate()

    controller = Controller(config)
    try:
        if not args.telemetry_thrift_only:
            controller.connect_all()
            connected = ", ".join(controller.connected_switch_names())
        else:
            connected = "thrift-only"
        status_stream = sys.stderr if args.telemetry_lock_ids and not args.telemetry_output else sys.stdout
        print(f"connected: {connected}", file=status_stream)
        if args.telemetry_lock_ids:
            lock_ids = _parse_lock_ids(args.telemetry_lock_ids)
            _run_telemetry_collection(
                controller=controller,
                lock_ids=lock_ids,
                interval_seconds=args.telemetry_interval,
                once=args.telemetry_once,
                output_path=Path(args.telemetry_output) if args.telemetry_output else None,
            )
        elif args.stay_connected:
            print("controller running; press Ctrl-C to stop")
            while True:
                time.sleep(1)
    except KeyboardInterrupt:
        print("stopping controller")
    finally:
        if not args.telemetry_thrift_only:
            controller.disconnect_all()
    return 0


def _parse_lock_ids(raw: str) -> list[int]:
    lock_ids = [int(part.strip()) for part in raw.split(",") if part.strip()]
    if not lock_ids:
        raise ValueError("--telemetry-lock-ids must contain at least one lock ID")
    if any(lock_id < 0 for lock_id in lock_ids):
        raise ValueError("lock IDs must be non-negative")
    return lock_ids


def _run_telemetry_collection(
    controller: Controller,
    lock_ids: list[int],
    interval_seconds: float,
    once: bool,
    output_path: Path | None,
) -> None:
    output = output_path.open("w", newline="", encoding="utf-8") if output_path else sys.stdout
    previous: dict[tuple[str, int], LockTelemetrySnapshot] = {}
    if interval_seconds <= 0:
        raise ValueError("telemetry interval must be positive")
    try:
        writer = csv.DictWriter(
            output,
            fieldnames=[
                "timestamp",
                "switch",
                "lock_id",
                "depth",
                "occupancy",
                "memory_waste_slots",
                "memory_waste_ratio",
                "acquire_count",
                "miss_count",
                "miss_ratio",
                "overflow_count",
                "queue_overflow_ratio",
                "acquire_delta",
                "miss_delta",
                "miss_ratio_delta",
                "overflow_delta",
                "queue_overflow_ratio_delta",
            ],
        )
        writer.writeheader()
        while True:
            timestamp = _utc_timestamp()
            for switch_name, snapshots in controller.collect_telemetry(lock_ids).items():
                for snapshot in snapshots:
                    key = (switch_name, snapshot.lock_id)
                    delta = (
                        LockTelemetryDelta.from_snapshots(previous[key], snapshot)
                        if key in previous
                        else None
                    )
                    writer.writerow(_telemetry_row(timestamp, switch_name, snapshot, delta))
                    previous[key] = snapshot
            output.flush()
            if once:
                break
            time.sleep(interval_seconds)
    finally:
        if output_path:
            output.close()


def _telemetry_row(
    timestamp: str,
    switch_name: str,
    snapshot: LockTelemetrySnapshot,
    delta: LockTelemetryDelta | None,
) -> dict[str, int | float | str]:
    return {
        "timestamp": timestamp,
        "switch": switch_name,
        "lock_id": snapshot.lock_id,
        "depth": snapshot.depth,
        "occupancy": snapshot.occupancy,
        "memory_waste_slots": snapshot.memory_waste_slots,
        "memory_waste_ratio": snapshot.memory_waste_ratio,
        "acquire_count": snapshot.acquire_count,
        "miss_count": snapshot.miss_count,
        "miss_ratio": snapshot.miss_ratio,
        "overflow_count": snapshot.overflow_count,
        "queue_overflow_ratio": snapshot.queue_overflow_ratio,
        "acquire_delta": delta.acquire_delta if delta else 0,
        "miss_delta": delta.miss_delta if delta else 0,
        "miss_ratio_delta": delta.miss_ratio if delta else 0.0,
        "overflow_delta": delta.overflow_delta if delta else 0,
        "queue_overflow_ratio_delta": delta.queue_overflow_ratio if delta else 0.0,
    }


def _utc_timestamp() -> str:
    return time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())


if __name__ == "__main__":
    raise SystemExit(main())
