from __future__ import annotations

from argparse import ArgumentParser
from pathlib import Path
from typing import Iterable
import time

try:
    from .config import ControllerConfig, PipelineConfig, SwitchConfig, load_controller_config
    from .p4runtime_switch import P4RuntimeSwitch
except ImportError:  # pragma: no cover - supports `python control_plane/controller.py`
    from config import ControllerConfig, PipelineConfig, SwitchConfig, load_controller_config
    from p4runtime_switch import P4RuntimeSwitch


class Controller:
    """Top-level control-plane process.

    The first milestone is connection management. Statistics collection,
    migration decisions, and table/register programming should be layered on
    top of this class through dedicated modules.
    """

    def __init__(self, config: ControllerConfig):
        self.config = config
        self.switches = {
            switch_config.name: P4RuntimeSwitch(switch_config)
            for switch_config in config.switches
        }

    def connect_all(self) -> None:
        for switch in self.switches.values():
            switch.connect()

    def disconnect_all(self) -> None:
        for switch in reversed(list(self.switches.values())):
            switch.disconnect()

    def connected_switch_names(self) -> list[str]:
        return [
            name
            for name, switch in self.switches.items()
            if switch.connected
        ]

    def __enter__(self) -> "Controller":
        self.connect_all()
        return self

    def __exit__(self, exc_type, exc, tb) -> None:
        self.disconnect_all()


def build_single_switch_config(args) -> ControllerConfig:
    pipeline = PipelineConfig(
        p4info_path=Path(args.p4info),
        bmv2_json_path=Path(args.bmv2_json),
    )
    switch = SwitchConfig(
        name=args.name,
        device_id=args.device_id,
        grpc_addr=args.grpc_addr,
        election_id=(args.election_id_high, args.election_id_low),
        pipeline=pipeline,
    )
    return ControllerConfig((switch,))


def parse_args(argv: Iterable[str] | None = None):
    parser = ArgumentParser(description="Multi-rack NetLock P4Runtime controller")
    parser.add_argument(
        "--config",
        type=str,
        help="Optional JSON controller config. If omitted, single-switch flags are used.",
    )
    parser.add_argument("--name", default="leaf1", help="Switch name for single-switch mode")
    parser.add_argument("--device-id", type=int, default=1, help="P4Runtime device_id")
    parser.add_argument(
        "--grpc-addr",
        default="127.0.0.1:50001",
        help="P4Runtime server address, e.g. 127.0.0.1:50001",
    )
    parser.add_argument(
        "--election-id-high",
        type=int,
        default=0,
        help="High 64 bits of P4Runtime controller election ID",
    )
    parser.add_argument(
        "--election-id-low",
        type=int,
        default=1,
        help="Low 64 bits of P4Runtime controller election ID",
    )
    parser.add_argument(
        "--p4info",
        default="build/leaf.p4info.txt",
        help="Path to text-format P4Info generated by p4c",
    )
    parser.add_argument(
        "--bmv2-json",
        default="build/leaf.json",
        help="Path to BMv2 JSON generated by p4c",
    )
    parser.add_argument(
        "--stay-connected",
        action="store_true",
        help="Keep the controller alive until Ctrl-C after connecting",
    )
    return parser.parse_args(argv)


def main(argv: Iterable[str] | None = None) -> int:
    args = parse_args(argv)
    config = load_controller_config(args.config) if args.config else build_single_switch_config(args)
    config.validate()

    controller = Controller(config)
    try:
        controller.connect_all()
        connected = ", ".join(controller.connected_switch_names())
        print(f"connected: {connected}")
        if args.stay_connected:
            print("controller running; press Ctrl-C to stop")
            while True:
                time.sleep(1)
    except KeyboardInterrupt:
        print("stopping controller")
    finally:
        controller.disconnect_all()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
